import { Sighting } from '../model/Sighting';
import { Organism } from '../model/Organism';

import { stubAtegamaNudibranch, stubBottlenoseDolphin, stubLemonShark, stubReefOctopus } from './organisms';
import { stubOrcaDolphin } from './organisms';

export const stubCurrentUserSightings = [
  new Sighting(
    '0',
    'Still here',
    'Houghton Bay',
    '11:15',
    6,
    stubBottlenoseDolphin,
    'Approx. 20',
    'Large pod playing',
    'Bay',
    undefined,
    'Playing',
    'Red Rocks',
    true,
    false,
  ),

  new Sighting(
    '1',
    'Gone',
    'Shelly Bay',
    '16:52',
    28,
    stubOrcaDolphin,
    '7',
    'Family with 5 juveniles',
    'Bay',
    undefined,
    'Hunting',
    'Evans Bay',
    true,
    true,
  ),

  new Sighting(
    '3',
    'Gone',
    'Little Karaka Bay',
    '10:00',
    3,
    stubAtegamaNudibranch,
    '1',
    'Feeding in tidal pool',
    'Tidal pool',
    undefined,
    'Feeding',
    undefined,
    true,
    false,
  ),

  new Sighting(
    '4',
    'Gone',
    'Oriental Parade',
    '15:03',
    55,
    stubLemonShark,
    'Approx. 10',
    'Around the restaurant',
    'Bay',
    undefined,
    'Unknown',
    undefined,
    true,
    true,
  ),

  new Sighting(
    '5',
    'Gone',
    'Red Rocks',
    '15:03',
    2,
    stubReefOctopus,
    '1',
    undefined,
    'Tidal pool',
    undefined,
    'Unknown',
    undefined,
    true,
    false,
  ),
];
